### ISSUE TITLE
Error Registering FID: Insufficient Gas

### ISSUE THREAD

**Issue by connormcmk** [wojtekwtf/farcaster-signup-demo#5]
I'm running this locally

I have $30 in ETH, is that not enough to register?

```
This error could arise when the account does not have enough funds to:
 - pay for the total gas fee,
 - pay for the value to send.
 
The cost of the transaction is calculated as `gas * gas fee + value`, where:
 - `gas` is the amount of gas needed for transaction to execute,
 - `gas fee` is the gas fee,
 - `value` is the amount of ether to send to the recipient.
 
Raw Call Arguments:
  from:   0x2aDfe609e3c4bdc298a086e0186E19E8be792B64
  to:     0x00000000Fc25870C6eD6b6c7E41Fb078b7656f69
  value:  0.001062921404048314 ETH
  data:   0x4420e4860000000000000000000000004f8c531df3d97c6cd437ac8dfe756975445d1161
 
Contract Call:
  address:   0x00000000Fc25870C6eD6b6c7E41Fb078b7656f69
  function:  register(address recovery)
  args:              (0x4f8c531df3d97c6Cd437aC8DfE756975445D1161)
  sender:    0x2aDfe609e3c4bdc298a086e0186E19E8be792B64

Docs: https://viem.sh/docs/contract/simulateContract.html
Details: err: insufficient funds for gas * price + value: address 0x2aDfe609e3c4bdc298a086e0186E19E8be792B64 have 0 want 1062921404048314 (supplied gas 550000000)
Version: viem@1.15.3
    at getContractError (getContractError.js:34:12)
    at simulateContract (simulateContract.js:81:98)
    at async prepareWriteContract (chunk-YAPWLAI7.js:2143:31)
```

**Comment by connormcmk** [comment]
nvm noticed it's not ETH on OP
